from enum import Enum

class ConnectorCapabilityStatus(str, Enum):
    SUPPORTED_AUTO_APPLY = "SUPPORTED_AUTO_APPLY"
    SUPPORTED_JOB_DISCOVERY_ONLY = "SUPPORTED_JOB_DISCOVERY_ONLY"
    EXTERNAL_APPLICATION_REQUIRED = "EXTERNAL_APPLICATION_REQUIRED"
    NOT_SUPPORTED = "NOT_SUPPORTED"

class ApplicationStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    MATCHED = "MATCHED"
    POLICY_PENDING = "POLICY_PENDING"
    POLICY_APPROVED = "POLICY_APPROVED"
    DUPLICATE = "DUPLICATE"
    BLOCKED = "BLOCKED"
    QUEUED = "QUEUED"
    PREPARING = "PREPARING"
    VALIDATING = "VALIDATING"
    SUBMITTING = "SUBMITTING"
    APPLIED = "APPLIED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    AUTO_APPLY_UNSUPPORTED = "AUTO_APPLY_UNSUPPORTED"
    EXTERNAL_APPLICATION_REQUIRED = "EXTERNAL_APPLICATION_REQUIRED"
    SUBMISSION_ATTEMPTED = "SUBMISSION_ATTEMPTED"
    SUBMISSION_CONFIRMED = "SUBMISSION_CONFIRMED"
    SUBMISSION_FAILED = "SUBMISSION_FAILED"
    MISSING_INFORMATION = "MISSING_INFORMATION"
    RATE_LIMITED = "RATE_LIMITED"
    EXPIRED = "EXPIRED"
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ONLINE_ASSESSMENT = "ONLINE_ASSESSMENT"
    INTERVIEWING = "INTERVIEWING"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    OFFER = "OFFER"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"

class PolicyDecision(str, Enum):
    AUTO_APPLY = "AUTO_APPLY"
    SKIP_LOW_MATCH = "SKIP_LOW_MATCH"
    SKIP_INELIGIBLE = "SKIP_INELIGIBLE"
    SKIP_DUPLICATE = "SKIP_DUPLICATE"
    SKIP_BLOCKED_COMPANY = "SKIP_BLOCKED_COMPANY"
    SKIP_BLOCKED_KEYWORD = "SKIP_BLOCKED_KEYWORD"
    SKIP_LOCATION = "SKIP_LOCATION"
    SKIP_SALARY = "SKIP_SALARY"
    SKIP_EXPERIENCE = "SKIP_EXPERIENCE"
    SKIP_DAILY_LIMIT = "SKIP_DAILY_LIMIT"
    AUTO_APPLY_UNSUPPORTED = "AUTO_APPLY_UNSUPPORTED"
    MISSING_INFORMATION = "MISSING_INFORMATION"

class QueueStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"

class SubmissionMethod(str, Enum):
    MANUAL = "MANUAL"
    EXTERNAL_PORTAL = "EXTERNAL_PORTAL"
    DIRECT_API = "DIRECT_API"
    MOCK_CONNECTOR = "MOCK_CONNECTOR"
    AUTOMATED_AGENT = "AUTOMATED_AGENT"

class ApplicationEventType(str, Enum):
    CREATED = "CREATED"
    APPLICATION_CREATED = "APPLICATION_CREATED"
    POLICY_APPROVED = "POLICY_APPROVED"
    QUEUED = "QUEUED"
    PREPARING = "PREPARING"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    SUBMISSION_STARTED = "SUBMISSION_STARTED"
    SUBMISSION_SUCCESS = "SUBMISSION_SUCCESS"
    SUBMISSION_FAILED = "SUBMISSION_FAILED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    AUTO_APPLY_UNSUPPORTED = "AUTO_APPLY_UNSUPPORTED"
    MISSING_INFORMATION = "MISSING_INFORMATION"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    RATE_LIMIT_REACHED = "RATE_LIMIT_REACHED"
    STATUS_CHANGED = "STATUS_CHANGED"
    EMAIL_RECEIVED = "EMAIL_RECEIVED"
    INTERVIEW_INVITED = "INTERVIEW_INVITED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    REJECTED = "REJECTED"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    NOTE_ADDED = "NOTE_ADDED"

class EmailProvider(str, Enum):
    GMAIL = "GMAIL"
    OUTLOOK = "OUTLOOK"
    IMAP = "IMAP"

class EmailClassification(str, Enum):
    INTERVIEW_INVITATION = "INTERVIEW_INVITATION"
    REJECTION = "REJECTION"
    OA_REQUEST = "OA_REQUEST"
    OFFER = "OFFER"
    GENERAL_INQUIRY = "GENERAL_INQUIRY"
    SPAM = "SPAM"
    UNCLASSIFIED = "UNCLASSIFIED"

class MailboxProviderType(str, Enum):
    GMAIL = "GMAIL"
    OUTLOOK = "OUTLOOK"
    MOCK = "MOCK"

class MailboxConnectionStatus(str, Enum):
    CONNECTED = "CONNECTED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    REFRESH_REQUIRED = "REFRESH_REQUIRED"
    NEEDS_REAUTH = "NEEDS_REAUTH"
    REVOKED = "REVOKED"
    DISCONNECTED = "DISCONNECTED"
    ERROR = "ERROR"
    SYNCING = "SYNCING"

class EmailCategory(str, Enum):
    JOB_APPLICATION = "JOB_APPLICATION"
    APPLICATION_CONFIRMATION = "APPLICATION_CONFIRMATION"
    RECRUITER_MESSAGE = "RECRUITER_MESSAGE"
    RECRUITER_OUTREACH = "RECRUITER_OUTREACH"
    INTERVIEW_INVITATION = "INTERVIEW_INVITATION"
    ASSESSMENT = "ASSESSMENT"
    ASSESSMENT_REQUEST = "ASSESSMENT_REQUEST"
    REJECTION = "REJECTION"
    OFFER = "OFFER"
    GENERAL_INQUIRY = "GENERAL_INQUIRY"
    FOLLOW_UP = "FOLLOW_UP"
    JOB_ALERT = "JOB_ALERT"
    OTHER_JOB_RELATED = "OTHER_JOB_RELATED"
    NOT_JOB_RELATED = "NOT_JOB_RELATED"

class RecruiterStatus(str, Enum):
    RECRUITER_DIRECT = "RECRUITER_DIRECT"
    ATS_SYSTEM = "ATS_SYSTEM"
    RECRUITER_CONFIRMED = "RECRUITER_CONFIRMED"
    RECRUITER_LIKELY = "RECRUITER_LIKELY"
    RECRUITER_UNKNOWN = "RECRUITER_UNKNOWN"
    NOT_RECRUITER = "NOT_RECRUITER"

class ApplicationMatchStatus(str, Enum):
    MATCHED = "MATCHED"
    LIKELY_MATCH = "LIKELY_MATCH"
    UNMATCHED = "UNMATCHED"
    AMBIGUOUS = "AMBIGUOUS"

class MailboxNotificationType(str, Enum):
    NEW_RECRUITER_EMAIL = "NEW_RECRUITER_EMAIL"
    INTERVIEW_INVITATION = "INTERVIEW_INVITATION"
    ASSESSMENT_RECEIVED = "ASSESSMENT_RECEIVED"
    APPLICATION_RESPONSE = "APPLICATION_RESPONSE"
    REJECTION_RECEIVED = "REJECTION_RECEIVED"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    MAILBOX_SYNC_ERROR = "MAILBOX_SYNC_ERROR"
    MAILBOX_REAUTH_REQUIRED = "MAILBOX_REAUTH_REQUIRED"

class RemoteType(str, Enum):
    REMOTE = "REMOTE"
    HYBRID = "HYBRID"
    ONSITE = "ONSITE"

class EmploymentType(str, Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERNSHIP = "INTERNSHIP"

class SkillCategory(str, Enum):
    TECHNICAL = "TECHNICAL"
    SOFT_SKILL = "SOFT_SKILL"
    TOOL = "TOOL"
    DOMAIN = "DOMAIN"

class ChatSenderType(str, Enum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"

class ChatContextType(str, Enum):
    GENERAL = "GENERAL"
    JOB_SPECIFIC = "JOB_SPECIFIC"
    APPLICATION_SPECIFIC = "APPLICATION_SPECIFIC"
    RESUME_SPECIFIC = "RESUME_SPECIFIC"

class NotificationType(str, Enum):
    EMAIL_CLASSIFIED = "EMAIL_CLASSIFIED"
    MATCH_FOUND = "MATCH_FOUND"
    STATUS_UPDATE = "STATUS_UPDATE"
    SYSTEM = "SYSTEM"

class UserRole(str, Enum):
    CANDIDATE = "CANDIDATE"
    ADMIN = "ADMIN"

class DraftIntent(str, Enum):
    SCHEDULE_INTERVIEW = "SCHEDULE_INTERVIEW"
    THANK_YOU = "THANK_YOU"
    NEGOTIATE_OFFER = "NEGOTIATE_OFFER"
    FOLLOW_UP = "FOLLOW_UP"
    ACCEPT_OFFER = "ACCEPT_OFFER"
    DECLINE_OFFER = "DECLINE_OFFER"
    COLD_REPLY = "COLD_REPLY"
    GENERAL = "GENERAL"

class DraftTone(str, Enum):
    PROFESSIONAL = "PROFESSIONAL"
    CONFIDENT = "CONFIDENT"
    ENTHUSIASTIC = "ENTHUSIASTIC"
    ASSERTIVE = "ASSERTIVE"
    CONCISE = "CONCISE"

class DraftStatus(str, Enum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    COPIED = "COPIED"
    SENT = "SENT"
    DISCARDED = "DISCARDED"

class RecruiterRelationshipStage(str, Enum):
    INITIAL_CONTACT = "INITIAL_CONTACT"
    SCREEN_SCHEDULED = "SCREEN_SCHEDULED"
    IN_PROCESS = "IN_PROCESS"
    OFFER_STAGE = "OFFER_STAGE"
    GHOSTED = "GHOSTED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"

class InterviewRoundType(str, Enum):
    TECHNICAL_SCREEN = "TECHNICAL_SCREEN"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    BEHAVIORAL = "BEHAVIORAL"
    HIRING_MANAGER = "HIRING_MANAGER"
    CODING_OA = "CODING_OA"
    PANEL = "PANEL"
    FINAL = "FINAL"

class InterviewStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"

class PlatformCapability(str, Enum):
    JOB_DISCOVERY = "JOB_DISCOVERY"
    APPLICATION_SUBMISSION = "APPLICATION_SUBMISSION"
    AUTO_APPLY = "AUTO_APPLY"
    APPLICATION_STATUS_TRACKING = "APPLICATION_STATUS_TRACKING"
    OAUTH_AUTH = "OAUTH_AUTH"
    WEBHOOK_NOTIFICATIONS = "WEBHOOK_NOTIFICATIONS"

class ConnectorStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    CONFIGURED = "CONFIGURED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTHORIZED = "AUTHORIZED"
    RATE_LIMITED = "RATE_LIMITED"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"
    EXTERNAL_APPLICATION_REQUIRED = "EXTERNAL_APPLICATION_REQUIRED"
    ERROR = "ERROR"

class AuthorizationType(str, Enum):
    OAUTH_2 = "OAUTH_2"
    API_KEY = "API_KEY"
    PARTNER_API = "PARTNER_API"
    NO_AUTH = "NO_AUTH"
    UNSUPPORTED = "UNSUPPORTED"

class AuditEventType(str, Enum):
    OAUTH_CONNECTED = "OAUTH_CONNECTED"
    OAUTH_DISCONNECTED = "OAUTH_DISCONNECTED"
    POLICY_CHANGED = "POLICY_CHANGED"
    AUTO_APPLY_TOGGLED = "AUTO_APPLY_TOGGLED"
    APPLICATION_ATTEMPT = "APPLICATION_ATTEMPT"
    APPLICATION_SUCCESS = "APPLICATION_SUCCESS"
    APPLICATION_FAILED = "APPLICATION_FAILED"
    CONNECTOR_CONFIGURED = "CONNECTOR_CONFIGURED"
    MAILBOX_CONNECTED = "MAILBOX_CONNECTED"
    MAILBOX_DISCONNECTED = "MAILBOX_DISCONNECTED"
    DRAFT_GENERATED = "DRAFT_GENERATED"
    DRAFT_APPROVED = "DRAFT_APPROVED"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"
    SECURITY_EVENT = "SECURITY_EVENT"

class SystemHealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"


